name: Build & Publish RSS (nightly)

on:
  schedule:
    - cron: "0 8 * * *"   # nightly 08:00 UTC
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # allow pushes to the repo

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build feed
        run: python build_feed.py

      - name: Commit rss.xml to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add rss.xml
          git commit -m "Update rss.xml $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push
