name: Build & Publish RSS (nightly)

on:
  schedule:
    - cron: "0 8 * * *"   # 08:00 UTC nightly
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build feed
        run: python build_feed.py

      - name: Switch to gh-pages branch
        run: |
          git fetch origin gh-pages || true
          if git show-ref --verify --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            git reset --hard
          fi

      - name: Copy output to gh-pages root
        run: |
          cp -f rss.xml index.xml
          # Keep rss.xml as canonical; index.xml is a convenience
          git add rss.xml index.xml

      - name: Commit & push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Publish nightly feed build $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "Nothing to commit"
          git push origin HEAD:gh-pages
